### ISSUE TITLE
Editable user site-packages installation no longer possible due to pyproject.toml and PEP-517

### ISSUE THREAD

**Issue by astoeckel** [nengo/nengo#1673] opened 2021-03-31 19:55 UTC
**Describe the bug**

I usually install development versions of Python packages such as nengo on my machine using
```sh
pip3 install --user -e .
```
This creates a `nengo.egg-link` file in `~/.local/lib/python3.9/site-packages`. The `~/.local` folder is the typical location for user-installed software on Linux/Unix.

Ever since the `pyproject.toml` file was added to the nengo repository, this no longer works. See below for the error message.

**To reproduce**

```sh
git clone https://github.com/nengo/nengo
cd nengo
pip3 install --user -e .
```
This will error out. After deleting the `pyproject.toml` file nengo installs just fine.

**Expected behavior**

The above command should install nengo.

**Error message and logs**

```
   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/andreas/source/nengo/setup.py'"'"'; __file__='"'"'/home/andreas/source/nengo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /home/andreas/source/nengo/
    Complete output (18 lines):
    running develop
    WARNING: The user site-packages directory is disabled.
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/usr/local/lib/python3.9'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /usr/local/lib/python3.9/site-packages/
    
    This directory does not currently exist.  Please create it and try again, or
    choose a different installation directory (using the -d or --install-dir
    option).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/andreas/source/nengo/setup.py'"'"'; __file__='"'"'/home/andreas/source/nengo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

**Versions**

 - OS: Fedora 33
 - Python: Python 3.9
 - Nengo: latest master

**Additional context**
See the following bug reports for more context:
* https://github.com/pypa/pip/issues/7953
* https://github.com/adafruit/cookiecutter-adafruit-circuitpython/issues/118

Apparently presence of the `pyproject.toml` file signals compliance with PEP-517, which in turn triggers some weird logic in pip that causes this issue from time to time.

**Comment by drasmuss** [comment] 2021-04-01 12:45
Following your reproduction steps works fine for me, no error and the package installs as you'd expect. So I suspect this is something specific to your environment, rather than something in `nengo`'s code. If you try to install other projects that use `pyproject.toml` (e.g. https://github.com/numpy/numpy), do you see the same error?

**Comment by jgosmann** [comment] 2021-04-01 15:39
I'm not sure, but PEP-517 [might not support editable installs](https://www.python.org/dev/peps/pep-0517/#get-requires-for-build-sdist). Maybe, it works with `pip install --no-use-pep517 ...`?

**Comment by astoeckel** [comment] 2021-04-01 18:55
I just tried this in a fresh Fedora 33 installation in a VM with the latest version of pip. I can reproduce the issue there.
Attempts at installing numpy from source error out with the same error message, `--no-use-pep517` fixes the issue.

So it is definitively not an issue with nengo, but an issue with the Python ecosystem moving to a new packaging standard ignoring the use case of people who do not use venvs and would like to use editable installations.

@drasmuss Just to make sure, did you try this outside a virtual environment? `--user` is generally ignored within venvs, as far as I am aware.

**Comment by drasmuss** [comment] 2021-04-01 19:10
I'm using Windows, so it's likely a difference there. In any case, since this seems to be an upstream issue with pip rather than Nengo I think we'll close this; people can follow the pip issue linked above for any updates on if/when they fix this.

In the meantime, if anyone wants to use `--user` but doesn't want to use virtual environments, they can work around it by using the `--no-use-pep517` flag.

Feel free to reopen if there's anything else though!

**Closed by drasmuss** 2021-04-01 19:10 UTC
