### ISSUE TITLE
Standardizing when, when not, and where to use the config system

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo#790] opened 2015-07-15 18:58 UTC
I'm trying to reorganize the associative memory network code to take full use of the config system (for an example see: [link](https://github.com/nengo/nengo/issues/780#issuecomment-120173547)). The idea being that if you don't specify a configuration, the network will build using whatever defaults the network designer (i.e. me) has put in, and if you do specify a configuration, it will use the configuration given.

In the examples below, the 'defaults' for the custom network are: max_rates=Uniform(10, 50), and encoders=Choice([[1]]). These can be overridden by the user.

<hr>

Method 1 (the 'old' way of doing it) - Put in all the possible changes to the network in the function definition:

```
def my_net(max_rates=Uniform(10, 50), encoders=Choice([[1]])):
    ... # Make the network
    with network:
        ens = nengo.Ensemble(..., max_rates=max_rates, encoders=encoders)
    ... # make the rest of the network
```

<hr>

Method 2 (using kwargs, and modifying the dictionary) - Used in the current AssociativeMemory code:

```
def my_net(**ens_kwargs):
    ... # Make the network
    with network:
        e_kwargs = dict(ens_kwargs)
        e_kwargs['max_rates'] = ens_kwargs.get('max_rates', Uniform(10, 50))
        e_kwargs['encoders'] = ens_kwargs.get('encoders', Choice([[1]]))
        ens = nengo.Ensemble(**e_kwargs)
    ... # make the rest of the network
```

<hr>

Method 3 (using kwargs, and updating the config) - Used in EnsembleArray:

```
def my_net(**ens_kwargs):
    ... # Make the network
    with network:
        network.config[nengo.Ensemble].update(ens_kwargs)
        ens = nengo.Ensemble(...)     
    ... # make the rest of the network
```

<hr>

Method 4 (pass in the config to use) - Used in Product:

```
def my_net(config=None):
    ... # Make the network

    if config is None:
        config = nengo.Config(nengo.Ensemble)
        config[nengo.Ensemble].max_rates = Uniform(10, 50)
        config[nengo.Ensemble].encoders = Choice([[1]])

    with nested(config, network):
        ens = nengo.Ensemble(...)     
    ... # make the rest of the network
```

Alternatively, I think this will work?

```
def my_net(config=None):
    ... # Make the network

    if config is None:
        config = nengo.Config()

    my_config = nengo.Config(nengo.Ensemble)
    my_config[nengo.Ensemble].max_rates = Uniform(10, 50)
    my_config[nengo.Ensemble].encoders = Choice([[1]])

    with nested(my_config, config, network):
        ens = nengo.Ensemble(...)     
    ... # make the rest of the network
```

*\* Sneak edit: corrected `nested(config, my_config, network)` to `nested(my_config, config, network)`
*\* Sneak edit 2: Added case where config is None.

<hr>

Method 5 (use the config from the parent network) - Used in BasalGanglia:

```
def my_net(net=None):
    ... # Make the network

    config = nengo.Config(nengo.Ensemble)
    config[nengo.Ensemble].max_rates = Uniform(10, 50)
    config[nengo.Ensemble].encoders = Choice([[1]])

    with nested(config, net):
        ens = nengo.Ensemble(...)
    ... # make the rest of the network
```

What is the 'standard' way of doing something like this?

**Comment by drasmuss** [comment] 2015-07-15 19:25
I like method 4 the best I think.  I think if all the user wants to do is change the parameters, it's easier to just create a new Config (method 4) than to create a new network and then modify its config (method 5).  

I think the difference between method 3 and 4 will just come down to what exactly is being configured.  If there are a bunch of parameters that all go together (e.g. parameters of an ensemble), then grouping them in a config makes sense (method 4).  If there are just one or two parameters that refer to different things in the network, then the more lightweight solution of method 3 might be preferable.  I don't think it would be so bad to have both of these coexisting, but if we had to choose one then method 4 seems more general, so I'd go with that.

**Comment by xchoo** [comment] 2015-07-15 19:25
Method 4a or b?

**Comment by drasmuss** [comment] 2015-07-15 19:31
4b seems better (allows users to change one part of the defaults, without having to repeat all the parts they don't want to change).

**Comment by jgosmann** [comment] 2015-07-15 19:43
I'd also vote 4b as a general method. But I think 3 is fine for simple cases like the `EnsembleArray` where it is clear that there is essentially only one config.

**Comment by xchoo** [comment] 2015-07-15 19:57
p.s. I added a few sneak edits to 4b... had to fix a few things. :sweat_smile:

**Comment by drasmuss** [comment] 2015-07-15 20:35
I don't know about the first sneaky edit, I liked it the way it was before. `with nested(my_config, config, network):` means that we're forcibly overwriting the user's config (`config`) right?  I think what we want is to give the config they pass in precedence, and only supply defaults for anything they didn't overwrite.  Which would be `with nested(config, my_config, network)`.

**Comment by xchoo** [comment] 2015-07-15 20:38
Oh. Did I get the precedence wrong again? I thought it was second config overwrites first config, and third config overwrites second and first? @tbekolay, @tcstewar?

**Comment by drasmuss** [comment] 2015-07-15 20:44
Wait nevermind I think you're right, I was just wrong about which order the `nested` parameters are evaluated in.  To be explicit, what we want is
```
with my_config:
    with config:
        with network:
            ....
```
I think we're on the same page.  Also i think you can just write it as `with config, my_config, network:` right?

**Comment by xchoo** [comment] 2015-07-15 20:45
> Wait nevermind I think you're right, I was just wrong about which order the nested parameters are evaluated in. To be explicit, what we want is
>```
with my_config:
    with config:
        with network:
            ....
```
Yup! That's the way we want it.

> I think we're on the same page. Also i think you can just write it as with my_network, config, my_config: right?
I'm not sure. Lemme test it.

**Comment by xchoo** [comment] 2015-07-15 20:46
Hmmm..  ```with my_network, config, my_config:``` seems to work. And if so, why do we have ```nested```?

**Comment by drasmuss** [comment] 2015-07-15 20:47
I think `nested` is just older syntax (pre 2.7).  Also I guess really we would want `with my_config, network, config`, in case we were also setting configs on the network (although that's probably something we should try to avoid to stop things from getting too confusing).

**Comment by xchoo** [comment] 2015-07-15 20:50
> in case we were also setting configs on the network

Haha. Yeah. That's method 3 from above. (and hence the point of this discussion. XD)

**Comment by Seanny123** [comment] 2015-07-21 18:09
In 4b, you still need to indent things so that the config is only set if there's no config passed in.

**Comment by xchoo** [comment] 2015-07-21 18:11
Uh. No, you don't. If I understand the config system correctly, doing this ```with nested(my_config, config, network):``` (or ```with my_config, config, network:```) means that things in ```config``` overrides```my_config```.

**Comment by Seanny123** [comment] 2015-07-21 18:14
Oh. I get it now. I didn't understand the difference between `config` and `my_config`. I also see how it changes the pull request #795, where I'm technically using 4b, but in a really weird synapse-specific way.

**Comment by tcstewar** [comment] 2015-07-21 18:29
There was a brief chat about this in the Nengo Dev meeting today, and I thought I'd write my summary here.

The main thing for me here is that I'm not sure that there are any cases where it makes sense to pass config object into functions/constructors.  My argument is basically that in order to understand what the config you pass in will actually modify, you really need to actually look at the code inside the function (and even then it can be unclear).  So I'd much rather have specific well-named input parameters that make it clear what things they will modify (for those things we expect novice users to want to modify), and for everything else people can modify the objects via the object model.

So, instead of doing
```
with model:
    product_config = nengo.Config(nengo.Ensemble)
    product_config[nengo.Ensemble].encoders = nengo.dists.UniformHypersphere(surface=True)    
    p = nengo.networks.Product(n_neurons=50, dimensions=4, config=product_config)
```

I think it's simpler to have an expert do this if they want to modify the encoders, since any expert wanting to muck with that parameter should know enough about the internals of the network to know what they are modifying:
```
with model:
    p = nengo.networks.Product(n_neurons=50, dimensions=4)
    for ens in p.all_ensembles:
        ens.encoders = nengo.dists.UniformHypersphere(surface=True)
```

and if we think we want to make that parameter a little more accessible, then we might introduce another parameter:

```
with model:
    p = nengo.networks.Product(n_neurons=50, dimensions=4, use_diagonal_encoders=False)
```

Notice that the parameter suggested there is more of a flag than a direct parameter for setting the encoders.  I prefer that to an ```encoders=``` parameter, as it's slighlty more customized to the reasons why this network was overriding the nengo default in the first place.

**Comment by Seanny123** [comment] 2015-07-21 18:35
If it doesn't make sense to pass config systems into constructors, what
heuristic should be used for when to use constructors?

**Comment by tcstewar** [comment] 2015-07-21 18:38
In any case, what I'd like to do is go through the existing networks and see what happens if they are re-written to be consistent with this approach.  I'm curious what functionality would be lost, and whether those are important conveniences.  

The basic principle I'm trying to stick with is that when you use the ```nengo.Config``` system in the normal way, nengo usually uses whatever parameters you specify.  Whenever it doesn't use those parameters, it's not using them for a reason (examples: the radius for a Product network, the synapse for an AMPA Connection).  So anyone wanting to change what a subnetwork is doing needs to understand a little bit about that subnetwork override its choices.  The two ways of doing that are input parameters (for things that we reasonably expect people would want to vary) and the object model (for anything else people could possibly want to vary).

**Comment by tcstewar** [comment] 2015-07-21 18:42
> If it doesn't make sense to pass config systems into constructors, what
> heuristic should be used for when to use constructors?

I don't think I understand the question.  I'm meant the argument to apply to both subnetworks defined with classes (i.e. constructors) and subnetworks defined with functions.  I'm saying to get rid of the config parameter into constructors and subnetwork functions, not anything about when to use constructors versus subnetwork functions.

**Comment by Seanny123** [comment] 2015-07-21 18:53
Gah, I really derped there. I meant, If it doesn't make sense to pass
config systems into constructors, what heuristic should be used for when to
use a *config*?

**Comment by drasmuss** [comment] 2015-07-21 19:15
@tcstewar That makes sense to me, presuming that we also go through and strip out uncommon parameters from the constructors of networks.  For me that was the reason to use configs, just as a way of getting rid of some of that clutter.  Getting rid of the arguments completely is a more radical (in both senses of the word) solution to that same problem.  I think this is what you had in mind anyway, I just want to make sure that we're on the same page that the goal is to reduce the complexity of the constructors in either case.

**Comment by tcstewar** [comment] 2015-07-21 19:15
> I meant, If it doesn't make sense to pass
> config systems into constructors, what heuristic should be used for when to
> use a *config*?

For the normal situations ```config``` is used for:

```python
with model:
    rate_config = nengo.Config(nengo.Ensemble)
    rate_config[nengo.Ensemble].neuron_type=nengo.LIFRate()
    spike_config = nengo.Config(nengo.Ensemble)
    spike_config[nengo.Ensemble].neuron_type=nengo.LIF()
    with rate_config:
         p1 = nengo.networks.Product(n_neurons=50, dimensions=4)
         a1 = nengo.Ensemble(n_neurons=10, dimensions=3)
    with spike_config:
         p2 = nengo.networks.Product(n_neurons=50, dimensions=4)
         a2 = nengo.Ensemble(n_neurons=10, dimensions=3)
```

Notice that even that is an advanced usage.  Most of the time people will just use the built-in ```nengo.Config``` that's attached to every Network:

```python
with model:
    rate_net = nengo.Network()
    rate_net.config[nengo.Ensemble].neuron_type=nengo.LIFRate()

    spike_net = nengo.Network()
    spike_net.config[nengo.Ensemble].neuron_type=nengo.LIF()

    with rate_net:
         p1 = nengo.networks.Product(n_neurons=50, dimensions=4)
         a1 = nengo.Ensemble(n_neurons=10, dimensions=3)

    with spike_net:
         p2 = nengo.networks.Product(n_neurons=50, dimensions=4)
         a2 = nengo.Ensemble(n_neurons=10, dimensions=3)
```

This is the sort of thing the ```Config``` system was designed for.  


The confusion arises, I think, in the cases where the subnetwork overrides whatever defaults were in the Config.  For anything that the subnetwork does not override, the Config system is fine and just goes ahead and modifies things to whatever the user has specified (different neuron_model, firing rates, synapse times, etc., etc.).  But, if the subnetwork is doing something special that requires or makes use of particular parameter settings, then it needs to set those itself, overriding whatever the user might have specified in their Config settings.

What this means is that the ```with config``` or ```with model``` settings are *defaults*, to be used only if nothing more specific overrides them.  That's why this works:

```python
model.config[nengo.Ensemble].encoders = nengo.dists.Choice([[1]])
with model:
    a = nengo.Ensemble(10, 1, encoders=nengo.dists.Choice([[1], [-1]])  # this does not use the config's default
```

Consistently, that's what happens when you use a subnetwork too:

```python
model.config[nengo.Ensemble].encoders = nengo.dists.Choice([[1]])
with model:
    p = nengo.networks.Product(10, 1)   # this does not use the config's default
```

Now, the question here is what to do when you want to override the subnetwork function's overridden variables.  The various examples above show a few different ways to do this, and one of them is by passing in ```nengo.Config``` objects.  This is possible to do, but I'm arguing that it might be clearer if instead we define a few well-named situation-specific parameters for the things people are likely to want to change, and for everything else (i.e. those things that the subnetwork is overriding for very good reasons) if people really want to change them they can go ahead and directly modify the object model.

**Comment by tbekolay** [comment] 2015-07-21 19:22
> Consistently, that's what happens when you use a subnetwork too:
> ```
> model.config[nengo.Ensemble].encoders = nengo.dists.Choice([[1]])
> with model:
>     p = nengo.networks.Product(10, 1)   # this does not use the config's default
> ```

This is a bit misleading; the only reason that the `Product` network doesn't use the default `encoders` set above is because `Product` overwrites them specifically. If you had set something else (e.g., `max_rates`) it would use those. Subnetworks still use the complete config context.

```python
model.config[nengo.Ensemble].encoders = nengo.dists.Choice([[1]])
model.config[nengo.Ensemble].max_rates = nengo.dists.Uniform(50, 150)
with model:
    # this does not use the model.config's default `encoders`,
    # but it does use the config's defualt max_rates.
    p = nengo.networks.Product(10, 1)
```

**Comment by tcstewar** [comment] 2015-07-21 19:28
> That makes sense to me, presuming that we also go through and strip out uncommon parameters from the constructors of networks. For me that was the reason to use configs, just as a way of getting rid of some of that clutter. Getting rid of the arguments completely is a more radical (in both senses of the word) solution to that same problem. I think this is what you had in mind anyway, I just want to make sure that we're on the same page that the goal is to reduce the complexity of the constructors in either case.

I definitely agree with going through and stripping out the uncommon parameters from the constructors.  I think if people want to do anything those uncommon parameters were for, well, we have an object model for a reason.  :)

It's not actually about clutter for me, though.  It's about making it clear what the effects of those parameters are.  It's very difficult to document when will happen when I create a Config and pass it in as a parameter, and it ends up being something like "Ensembles x, q, and p will use the nengo default parameters for all values except for encoders, which they will take from the passed-in config, unless the passed-in config doesn't define encoders, in which case it will use nengo.dists.Choice([[1]])".  I'd much prefer to have the documentation say "Ensembles x, q, and p will use the nengo default parameters for all values except for encoders, which will be nengo.dists.Choice([[1]])" or have some other parameter like ```use_positive_only_encoders``` if this is something that is likely to be changed.

That said, I also believe that getting rid of passing in configs can make the implementation code a little bit less cluttered, but that's a secondary concern for me.  And I don't mind having lots of parameters for the constructor/function, as long as the effects of those parameters are clear (but I'd still like to keep the parameters down to a reasonable number)

**Comment by tcstewar** [comment] 2015-07-21 19:30
> This is a bit misleading; the only reason that the Product network doesn't use the default encoders set above is because Product overwrites them specifically. If you had set something else (e.g., max_rates) it would use those. Subnetworks still use the complete config context.

Oops, sorry, I was a bit unclear there...  the point you're making is exactly what I wanted to point out.  The ```config``` stuff gets used for everything that the subnetworks don't override.  I should have done an example like you did where some things are overriden and some aren't.  I think I'll go back an d edit the example....

**Comment by Seanny123** [comment] 2015-08-19 20:39
To summarize what I've understood so far from this conversation:
- there's no reason to pass a config in as an argument and this should be removed from the code
- anything that used to be passed in as a config, if specific enough, will now be a keyword arg

My one (mild, possibly misguided concern) is the fact that over-riding something might unpleasantly surprise the user. From the Product network example above, I feel like the encoders being over-written should be notified to the user without them having to read the documentation.

My naive solution to this is to thrown a warning when a config is over-written (don't know how I would code this), but also give an option for the config to not throw warnings. Is this way too much trouble for what is a really obscure case?

**Comment by tcstewar** [comment] 2015-08-19 20:48
> My one (mild, possibly misguided concern) is the fact that over-riding something might unpleasantly surprise the user. From the Product network example above, I feel like the encoders being over-written should be notified to the user without them having to read the documentation.
> My naive solution to this is to thrown a warning when a config is over-written (don't know how I would code this), but also give an option for the config to not throw warnings. Is this way too much trouble for what is a really obscure case?

It's not an obscure case.  This is simply how the config system works.  We have to be clear in the documentation and tutorials for the config system that what you're configuring is the DEFAULT value -- i.e. the value that will be used if nothing is specified.  And that if you're using custom networks (like Product or Compare) then they'll probably specify a few things.  But we really don't want to have warnings all over the place, since this is exactly what the config system is supposed to do.  Having a warning like that would mean that all the specified synapses in the BasalGanglia would cause a warning, for example.

**Comment by Seanny123** [comment] 2015-08-19 20:49
Thanks for the explanation. I agree with just being specific in the config
documentation.

**Comment by tbekolay** [comment] 2016-12-14 15:59
The document this label is now valid for closed issues, so closing this as I think issue resolved itself save for the fact that it's not fully documented anyway. My thought is that this should end up being documented in the repo that results from splitting off the Nengo networks to a separate repo.

**Closed by tbekolay** 2016-12-14 15:59 UTC
Labels: document this
