### ISSUE TITLE
Fix spa.AssociativeMemory documentation (and add a few examples)

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo#885] opened 2015-10-22 20:03 UTC
I was trying to use the `spa.AssociativeMemory` as a basic dictionary and was having the darnest time. The code to finally get this scenario to work is:

The reasons I couldn't figure this out on my own is:
- There are no associative memory examples in the docs
- The arguments `input_keys` and `output_keys` are undocumented

**Comment by ikajic** [comment] 2015-11-03 20:51
I'm just going through this. First, I'm getting an `AttributeError` which I think I shouldn't be getting:
```python
In [4]: spa.AssociativeMemory(np.arange(10))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-e7f05435fee3> in <module>()
----> 1 spa.AssociativeMemory(np.arange(10))

/home/ivana/phd/workspace/nengo/nengo/spa/assoc_mem.pyc in __init__(self, input_vocab, output_vocab, input_keys, output_keys, default_output_key, threshold, input_scale, inhibitable, inhibit_scale, wta_output, wta_inhibit_scale, wta_synapse, threshold_output, label, seed, add_to_container, **ens_args)
     66 
     67         if input_keys is None:
---> 68             input_keys = input_vocab.keys
     69             input_vectors = input_vocab.vectors
     70         else:

AttributeError: 'numpy.ndarray' object has no attribute 'keys'
```

If the input is `spa.Vocabulary` it works, so it smells of a bug. What is the rationale behind keys when using a numpy.array?

**Comment by xchoo** [comment] 2015-11-03 20:54
The ```spa.AssociativeMemory``` network is expecting a vocabulary as an input. If you want to use vectors (or numpy arrays), try the ```networks.AssociativeMemory``` network. (The spa network is just a wrapper for the networks network)

**Comment by ikajic** [comment] 2015-11-03 20:57
Hm, the documentation for `spa.AssociativeMemory`says something different:
```
input_vocab: list of numpy.array, spa.Vocabulary
    The vocabulary (or list of vectors) to match.
```
So, even if I put a list of numpy arrays it throws the same error.

**Comment by xchoo** [comment] 2015-11-03 21:00
Oh. Hah! Whoops. That's an error in the documentation.

**Comment by s72sue** [comment] 2015-11-03 21:03
+1 for adding some associative memory examples to the docs.

**Comment by ikajic** [comment] 2015-11-03 21:06
Alright. I'll take care of fixing the docstrings and put a few examples in there.

**Comment by ikajic** [comment] 2015-11-05 19:00
What is the purpose of `add_to_container` parameter in `spa.AssociativeMemory`?

Elsewhere I found this description:
```
    add_to_container : bool, optional
        Whether this network will be added to the current context.
```
but I don't understand what that really means.

**Comment by tbekolay** [comment] 2015-11-05 19:17
`add_to_container` is a pretty niche thing that's buried deep in how Nengo manages objects. The part of code where it comes into play is [here](https://github.com/nengo/nengo/blob/master/nengo/network.py#L91).

The idea is that when you make `Ensemble`s, `Node`s, `Network`s, etc, they have to be contained within a network somewhere. There was a lot of talk about how to make sure that this is the case. One option would be to has the user call `add` every time they made an object. E.g.,

```python
net = nengo.Network()
ens = net.add(nengo.Ensemble(10, 1))
node = net.add(nengo.Node())
net.add(nengo.Connection(node, ens))
```

This was seen as needless verbose, so instead we opted to use Python's context management system (i.e., the `with` statement). So, the above snippet becomes

```python
net = nengo.Network()
with net:
    ens = nengo.Ensemble(10, 1)
    node = nengo.Node()
    nengo.Connection(node, ens)
```

Under the hood those two snippets do exactly the same thing.

The place where `add_to_container comes in is this: what if you don't actually want to add an object to the network? There are some fringe cases where you might want to do this, though they are admittedly pretty rare. But, we have to account for them regardless. So, all of the base objects (Ensemble, Node, etc) has a semi-hidden argument `add_to_container`. If you set this to `False`, then even in a `with` block, the object won't be added to the `Network` that you would normally be added to.

```python
with net:
    ens2 = nengo.Ensemble(10, 1)  # stored in net.ensembles
    ens3 = nengo.Ensemble(10, 1, add_to_container=False)  # not stored in a network; only accessible with ens3
```

All of the object except `Network` have this semi-hidden with metaclasses and other magic. But, we want people to build their own networks, which might mean subclassing `Network`, so we expose the `add_to_container` stuff in [`Network.__init__`](https://github.com/nengo/nengo/blob/master/nengo/network.py#L75).

This should definitely be better documented somewhere though (could copy/paste this comment to somewhere in the docs), and the name `add_to_container` is a bit misleading. It probably should have been `add_to_network` or `autoadd` or something like that.

**Comment by ikajic** [comment] 2015-11-05 20:04
Yeah, I was assuming this, but what confused me was the default  `None` as I was expecting to see `True` somewhere for an object created within a context.
Obviously, as you pointed out, this setting happens under the hood, as it can only be done when an object is added to the network. Thanks for the explanation, makes sense.

**Comment by jgosmann** [comment] 2016-11-25 20:47
Closing this as a duplicate of #1120. (This issue is older, but the other one is more concise in pointing out the problem.)

**Closed** 2016-11-25 20:48 UTC
Labels: document this, SPA
