### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isupper' 

### ISSUE THREAD

**Issue by assadRasheed** [nengo/nengo#1408] opened 2018-01-23 19:49 UTC
i tried to run the following code from your repository with out changing any single line but the above mention errors appears. i tried to rectify this but failed.

```python
from __future__ import print_function

import os

import nengo
import nengo_ocl
import numpy as np

from nengo_extras.data import load_cifar10
from nengo_extras.cuda_convnet import CudaConvnetNetwork, load_model_pickle
from nengo_extras.gui import image_display_function



(X_train, y_train), (X_test, y_test), label_names = load_cifar10(label_names=True)
X_train = X_train.reshape(-1, 3, 32, 32).astype('float32')
X_test = X_test.reshape(-1, 3, 32, 32).astype('float32')
n_classes = len(label_names)

# crop data
X_train = X_train[:, :, 4:-4, 4:-4]
X_test = X_test[:, :, 4:-4, 4:-4]

# subtract mean
data_mean = X_train.mean(axis=0)
X_train -= data_mean
X_test -= data_mean

# retrieve from https://figshare.com/s/49741f9e2d0d29f68871
cc_model = load_model_pickle('cifar10-lif-1628.pkl')


# --- Run model in Nengo
presentation_time = 0.2

model = nengo.Network()
with model:
    u = nengo.Node(nengo.processes.PresentInput(X_test, presentation_time))
    ccnet = CudaConvnetNetwork(cc_model, synapse=nengo.synapses.Alpha(0.005))
    nengo.Connection(u, ccnet.input, synapse=None)

    input_p = nengo.Probe(u)
    output_p = nengo.Probe(ccnet.output)

    # --- image display
    image_shape = X_test.shape[1:]
    display_f = image_display_function(image_shape, scale=1, offset=data_mean)
    display_node = nengo.Node(display_f, size_in=u.size_out)
    nengo.Connection(u, display_node, synapse=None)

    # --- output spa display
    vocab_names = [s.upper() for s in label_names]
    print(vocab_names)
    vocab_vectors = np.eye(len(vocab_names))

    vocab = nengo.spa.Vocabulary(len(vocab_names))
    
    
    for name, vector in zip(vocab_names, vocab_vectors):
        vocab.add(name, vector)

    config = nengo.Config(nengo.Ensemble)
    config[nengo.Ensemble].neuron_type = nengo.Direct()
    with config:
        output = nengo.spa.State(len(vocab_names), subdimensions=10, vocab=vocab)
    nengo.Connection(ccnet.output, output.input)


n_presentations = 100

if 0:
    # run ANN in Theano
    os.environ['THEANO_FLAGS'] = 'device=gpu,floatX=float32'
    Q = ccnet.theano_compute(X_test[:n_presentations])
    Z = np.argmax(Q, axis=-1) == y_test[:n_presentations]
    print("ANN accuracy (%d examples): %0.4f" % (n_presentations, Z.mean()))


with nengo_ocl.Simulator(model) as sim:
    sim.run(n_presentations * presentation_time)

nt = int(presentation_time / sim.dt)
blocks = sim.data[output_p].reshape(n_presentations, nt, n_classes)
choices = np.argmax(blocks[:, -20:, :].mean(axis=1), axis=1)
accuracy = (choices == y_test[:n_presentations]).mean()
print('Spiking accuracy (%d examples): %0.3f' % (n_presentations, accuracy))
```
**### when i run above code it give following error**
```
[b'AIRPLANE', b'AUTOMOBILE', b'BIRD', b'CAT', b'DEER', b'DOG', b'FROG', b'HORSE', b'SHIP', b'TRUCK']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-766cbc6b7cfe> in <module>()
     58 
     59     for name, vector in zip(vocab_names, vocab_vectors):
---> 60         vocab.add(name, vector)
     61 
     62     config = nengo.Config(nengo.Ensemble)

~\Anaconda3.0\lib\site-packages\nengo\spa\vocab.py in add(self, key, p)
    157                                     "read-only vocabulary." % key)
    158 
--> 159         if not key[0].isupper():
    160             raise SpaParseError(
    161                 "Semantic pointers must begin with a capital letter.")

AttributeError: 'int' object has no attribute 'isupper'
```

**Comment by tbekolay** [comment] 2018-01-23 20:00
That example is part of `nengo_extras`; could you open an issue [there](https://github.com/nengo/nengo_extras/issues/new) instead?

**Comment by jgosmann** [comment] 2018-01-23 20:17
The problem is that the names that get loaded are `bytes` objects, but `vocab.add` expects `str` objects. As a workaround you can convert the `bytes` objects to `str` objects with the `decode` method yourself. For example, you can try to insert this line:
```python
vocab_names = [name.decode('ascii') for name in vocab_names]
```
(You might want to chose an encoding different than `ascii` depending on the actual encoding of the names.)

**Comment by assadRasheed** [comment] 2018-01-24 08:40
**a new error arises when i ran the above code with suggested correction**

RuntimeError                              Traceback (most recent call last)
<ipython-input-1-ebe41d061ca0> in <module>()
     81 
     82 
---> 83 with nengo_ocl.Simulator(model) as sim:
     84     sim.run(n_presentations * presentation_time)
     85 

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in __init__(self, network, dt, seed, model, context, n_prealloc_probes, profiling, if_python_code, planner, progress_bar)
    306         with Timer() as plans_timer:
    307             for op_type, op_list in op_groups:
--> 308                 plans.extend(self.plan_op_group(op_type, op_list))
    309             plans.extend(self.plan_probes())
    310 

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in plan_op_group(self, op_type, ops)
    600 
    601     def plan_op_group(self, op_type, ops):
--> 602         return getattr(self, 'plan_' + op_type.__name__)(ops)
    603 
    604     def plan_PreserveValue(self, ops):  # LEGACY

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in plan_SimProcess(self, all_ops)
    930                 python_ops.extend(ops)
    931 
--> 932         process_plans = [p for attr, ops in iteritems(plan_groups)
    933                          for p in getattr(self, attr)(ops)]
    934         python_plans = [p for op in python_ops

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in <listcomp>(.0)
    931 
    932         process_plans = [p for attr, ops in iteritems(plan_groups)
--> 933                          for p in getattr(self, attr)(ops)]
    934         python_plans = [p for op in python_ops
    935                         for p in self._plan_python_process(op)]

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in _plan_Conv2d(self, ops)
   1024             plans.append(plan_conv2d(
   1025                 self.queue, X, Y, F, B, p.shape_in, p.shape_out,
-> 1026                 kernel_shape, conv, p.padding, p.strides))
   1027 
   1028         return plans

~\Anaconda3.0\lib\site-packages\nengo_ocl\clra_nonlinearities.py in plan_conv2d(queue, X, Y, filters, biases, shape_in, shape_out, kernel_shape, conv, padding, strides, tag, transposed)
   1642 
   1643     full_args = (X.base_data, filters.data, biases.data, Y.base_data)
-> 1644     _fn = cl.Program(queue.context, text).build().conv2d
   1645     _fn.set_args(*full_args)
   1646 

~\Anaconda3.0\lib\site-packages\pyopencl\__init__.py in build(self, options, devices, cache_dir)
    460                         self._context, self._source, options_bytes, devices,
    461                         cache_dir=cache_dir, include_path=include_path),
--> 462                     options_bytes=options_bytes, source=self._source)
    463 
    464             if was_cached:

~\Anaconda3.0\lib\site-packages\pyopencl\__init__.py in _build_and_catch_errors(self, build_func, options_bytes, source)
    504         # Python 3.2 outputs the whole list of currently active exceptions
    505         # This serves to remove one (redundant) level from that nesting.
--> 506         raise err
    507 
    508     # }}}

RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - 

Build on <pyopencl.Device 'Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz' on 'Intel(R) OpenCL' at 0xa0e86ec>:

Compilation started
:24:11: error: invalid operands to binary expression ('const __global float *' and 'double')
:25:11: error: invalid operands to binary expression ('__global float *' and 'double')
Compilation failed

(options: -I "c:\users\zaid-pc\anaconda3.0\lib\site-packages\pyopencl\cl")
(source saved as C:\Users\zaid-pc\AppData\Local\Temp\tmpkcv6swib.cl)

**Comment by jgosmann** [comment] 2018-01-24 15:04
@hunse, this seems to be related to Nengo OCL.

**Comment by hunse** [comment] 2018-01-31 17:44
It looks like you're trying to target your CPU with Nengo OCL. This won't be much faster than the nengo reference simulator, so I'd just use that. i.e. call ``nengo.Simulator(model)`` instead of ``nengo_ocl.Simulator(model)`` in the above code.

**Comment by assadRasheed** [comment] 2018-02-08 18:45
```
data_mean = X_train.mean(axis=0)
X_train -= data_mean
X_test -= data_mean

# retrieve from https://figshare.com/s/49741f9e2d0d29f68871
cc_model = load_model_pickle('cifar10-lif-1628.pkl')


# --- Run model in Nengo
presentation_time = 0.2
```
when i try to run the above code it require to download the **cifar10-lif-1628.pkl** file .what is in this file.why this file is necessary .when we try to run other datasets  how we can obtained file like that.

**Comment by Seanny123** [comment] 2018-02-08 20:08
@assadRasheed this isn't really relate to the current issue you're commenting on. May I recommend instead asking this question on forum.nengo.ai?

**Comment by jgosmann** [comment] 2018-06-12 15:35
This doesn't seem to be a Nengo problem, so I am closing this issue. Feel free to reopen if there is still an issue.

**Closed by jgosmann** 2018-06-12 15:35 UTC
