### ISSUE TITLE
Can neurons in nengo be classified as inhibitory-neuron and excitatory-neuron?

### ISSUE THREAD

**Issue by ParrtZhang** [nengo/nengo#1420] opened 2018-03-19 11:45 UTC
Hello professor

I have a question:
Can neurons in nengo be classified as inhibitory-neuron and excitatory-neuron?
If can , what should I operate?

Thanks for your review!

**Comment by Seanny123** [comment] 2018-03-19 13:33
Whether a neuron is inhibitory or excitatory can be decided by the sign of it's decoder or output weight. Do you know how to get the decoders of an ensemble of neurons?

**Comment by ParrtZhang** [comment] 2018-03-19 13:39
Can you teach me?

**Comment by Seanny123** [comment] 2018-03-19 14:56
Let's move this discussion to the forum, since this isn't really an issue with the Nengo code?

**Comment by ParrtZhang** [comment] 2018-03-20 11:32
I can't get on this website

**Comment by Seanny123** [comment] 2018-03-20 11:42
What do you mean by that? Does the link not work? Is the website down?

**Comment by ParrtZhang** [comment] 2018-03-20 11:49
The reason may be that I am in China,,so..I can't go on this website

**Comment by Seanny123** [comment] 2018-03-20 12:45
This seems unlikely. I tested access to forum.nengo.ai from a few Chinese servers and a number of our existing user's IPs originate from China.

**Comment by Seanny123** [comment] 2018-06-11 13:35
I'm going to go ahead and close this issue, since there hasn't been any activity in three months. Feel free to reopen if the issue is not resolved.

**Closed by Seanny123** 2018-06-11 13:35 UTC
