### ISSUE TITLE
Hetero-associative relationships in spa.AssociativeMemory

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo#891] opened 2015-11-04 19:28 UTC
From the current `spa.AssociativeMemory` documentation:

```
input_vocab: list of numpy.array, spa.Vocabulary
    The vocabulary (or list of vectors) to match.
output_vocab: list of numpy.array, spa.Vocabulary, optional
    The vocabulary (or list of vectors) to be produced for each match. If
    not given, the associative memory will act like an auto-associative
    memory (cleanup memory).
```

one could conclude that when the `output_vocab` is passed the memory should act like a hetero-associative memory, fairly standard use-case. By definition, this means that the network outputs a different stored pattern from the presented one, and this relationship is somehow stored in the network weights.
Now, when I try to use `spa.AssociativeMemory` in this way, this mapping doesn't happen.
Here a simple example:

``` python
import nengo
from nengo import spa
import matplotlib.pyplot as plt

vocab_input = spa.Vocabulary(dimensions=16)
vocab_output = spa.Vocabulary(dimensions=16)

vocab_input.parse('ONE + TWO')
vocab_output.parse('TWO + ONE')

with nengo.Network('model', seed=1) as model:
    assoc_mem = spa.AssociativeMemory(input_vocab=vocab_input, output_vocab=vocab_output)

    input_node = nengo.Node(output=vocab_input['ONE'].v, label='input')
    nengo.Connection(input_node, assoc_mem.input)

    input_probe = nengo.Probe(input_node)
    output_probe = nengo.Probe(assoc_mem.output, synapse=0.03)

sim = nengo.Simulator(model)
sim.run(.5)
t = sim.trange()

input_net = sim.data[input_probe]
output_net = sim.data[output_probe]

plt.figure(figsize=(16, 4))
plt.subplot(1, 2, 1)
plt.plot(t, nengo.spa.similarity(input_net, vocab_input))
plt.title("Input similarity")
plt.xlabel('Time')
plt.ylim(top=1.1)
plt.legend(vocab_input.keys, loc='best')
plt.subplot(1, 2, 2)
plt.plot(t, nengo.spa.similarity(output_net, vocab_output))
plt.title("Output similarity")
plt.xlabel('Time')
plt.legend(vocab_output.keys, loc='best')

plt.show()
```

For a hetero-associative memory I would expect to see "TWO" in the second plot.

Now, is what is currently happening really the intended behaviour? If it really is, what is the idea behind it?

**Comment by xchoo** [comment] 2015-11-04 19:44
Yup. This is intended behaviour. The associative memory network (AM for short) works with vocabularies and vocabulary keys. The idea being that if you provide 2 distinct vocabularies, it will try to map vocab1['key1'] to vocab2['key1'] (i.e. 'A' in one vocabulary to 'A' in the other).

If you really wanted to map (as in your example) 'ONE' from vocab1 to 'TWO' from vocab2, you'd have to use the ```input_keys``` and ```output_keys``` parameters.

```assoc_mem = spa.AssociativeMemory(input_vocab=vocab_input, input_keys=['ONE', 'TWO'], output_vocab=vocab_output, output_keys=['TWO', 'ONE'])```

**Comment by jgosmann** [comment] 2015-11-04 19:46
To clarify: 

> that the network outputs a different stored pattern from the presented one

This is what happens, because the patterns are the vectors which differ for the two vocabs. `ONE` in `vocab_input` is a different vector/pattern than `ONE` in `vocab_output`. But what one might expect is that `ONE` in `vocab_input` gets mapped to `TWO` in `vocab_output`. This raises a couple of questions.

1. Do we currently have an easy way to do such a mapping from a set of semantic pointers to another set of semantic pointers? If not, is this a potential use case and should we add something like this?
2. It seems there are currently two ways to transform from one vocab to another (different vectors, but same keys in this case): The `Vocabulary.transform_to` function can be used to create a projection to use as transform in connections, but the associative memory can be used in the same way. It seems like the `transform_to` method is better (it adds no neurons and I believe it's mathematically equivalent to the associative memory procedure). But why do we have this ability then duplicated in the associative memory? (Especially if it does not allow the mapping to a vocab with different keys.)
3. If we add the possibility how is the mapping specified? Relying on the order in the vocab seems brittle as the parse order might easily change.

**Comment by jgosmann** [comment] 2015-11-04 19:47
@xchoo  `spa.AssociativeMemory` does not have `input_keys` and `output_keys` arguments.

**Comment by jgosmann** [comment] 2015-11-04 19:47
Sorry, I'm wrong, it has, but they are undocumented.

**Comment by xchoo** [comment] 2015-11-04 19:47
Yeah it does. Not documented though.. haha

**Comment by jgosmann** [comment] 2015-11-04 19:54
I guess, that answers most of the questions. Still wondering, what would be a use case to map `vocab1['key1']` to `vocab2['key1']` if one could use a transform?

**Comment by jgosmann** [comment] 2015-11-04 19:54
(and we need better documentation)

**Comment by xchoo** [comment] 2015-11-04 19:55
> 1. Do we currently have an easy way to do such a mapping from a set of semantic pointers to another set of semantic pointers? If not, is this a potential use case and should we add something like this?

We can use the AM network for that. 
```assoc_mem = spa.AssociativeMemory(input_vocab=vocab_input, input_keys=vocab_input.keys, output_vocab=vocab_output, output_keys=vocab_output.keys)```

**Comment by xchoo** [comment] 2015-11-04 19:56
> It seems there are currently two ways to transform from one vocab to another (different vectors, but same keys in this case): The Vocabulary.transform_to function can be used to create a projection to use as transform in connections, but the associative memory can be used in the same way. It seems like the transform_to method is better (it adds no neurons and I believe it's mathematically equivalent to the associative memory procedure). But why do we have this ability then duplicated in the associative memory? (Especially if it does not allow the mapping to a vocab with different keys.)

The ```transform_to``` function isn't quite equivalent to the associative memory function. It also adds extra noise to the system.

**Comment by jgosmann** [comment] 2015-11-04 19:57
> The transform_to function isn't quite equivalent to the associative memory function. It also adds extra noise to the system.

What if you do the transform and cleanup the result or cleanup the input and then do the transform?

**Comment by xchoo** [comment] 2015-11-04 19:58
> 3. If we add the possibility how is the mapping specified? Relying on the order in the vocab seems brittle as the parse order might easily change.

This is why the AM code deals with key values, not the arbitrary order that the keys are defined in the vocabulary.

**Comment by xchoo** [comment] 2015-11-04 20:09
> What if you do the transform and cleanup the result or cleanup the input and then do the transform?

Cleaning up the result of the transform is the same as cleaning up the input vector. 

Cleaning up the input, and then performing the transform is not the same as just doing a cleanup.

The ```transform_to``` operation does (assuming A1 is ```vocab1['A'].v``` and A2 is ```vocab2['A'].v```):

dot(A1, A1) * A2 + dot(A1, B1) * B2 + dot(A1, C1) * C2 + ... + dot(A1, Z1) * Z2

whereas the cleanup operation is:
(let cleanup(x) = if x < threshold? 0 : 1)
cleanup(dot(A1, A1)) * A2 + cleanup(dot(A1, B1)) * B2 + cleanup(dot(A1, C1)) * C2 + ... + cleanup(dot(A1, Z1)) * Z2

**Comment by xchoo** [comment] 2015-11-04 20:23
> (and we need better documentation)

Yeah. That's what issue #885 is for.

**Comment by ikajic** [comment] 2015-11-04 20:30
Thanks for clarifying. Specifying the keys certainly makes it more clear what is going on.

Since the creation of associative memory is very straight-forward:
```
mem = spa.AssociativeMemory(vocab)
```
one could expect that creating a hetero-associative memory shouldn't be much different, so it feels intuitive to go for:
```
mem = spa.AssociativeMemory(vocab1, vocab2)
```
Of course, now I am talking about the expected behaviour of AMs without knowing details of implementation, assuming that's how someone not familiar with the SPA but familiar with AMs might approach this.
As Jan pointed out, when knowing the details of implementation, this is perfectly valid and the outcome makes sense. But I still find it rather confusing (but maybe just because of the way it's documented now).
So, my question is, why:
```
mem = spa.AssociativeMemory(vocab1, vocab2)
```
by default shouldn't do mapping from `vocab1.keys` to `vocab2.keys`? :)

**Comment by xchoo** [comment] 2015-11-04 20:34
> So, my question is, why:
> ```mem = spa.AssociativeMemory(vocab1, vocab2)```
> by default shouldn't do mapping from ```vocab1.keys``` to ```vocab2.keys```? :)

Jan sort of alluded to it in his comment. It's because the order of the keys in each vocabulary is dependent on the order of creation of the keys. This can be arbitrary and dependent on the code used. It makes more sense to (and this needs to be documented) use a constant (i.e. the key value) from both vocabularies as a standard to do the mapping.

**Comment by ikajic** [comment] 2015-11-04 20:41
I see. So, the order in which the keys are created does not necessarily reflect the desired mapping. Yup, that makes sense!

**Comment by jgosmann** [comment] 2015-11-04 20:48
> Cleaning up the input, and then performing the transform is not the same as just doing a cleanup.

I think, it almost is and the only reason that it is not is that the semantic pointers won't be perfectly orthonormal.

Using matrix notation we can denote the semantic pointers in the two vocabs with V1 and V2 (rows are semantic pointers, columns dimensions in the representation). Let x be the input vector that should be transformed from V1 to V2. Then the transform should be given by

((V1 • x)^T • V2)^T = V2^T • V1 • x

The cleanup operation should be given by

(f(V1 • x)^T • V2)^T = V2^T • f(V1 • x)

where f(.) is the thresholding.

Now using an auto-associative cleanup with a transform afterwards we get

V2^T • V1 • V1^T • f(V1 • x).

Assuming orthonormal semantic pointers (which should be ok for a reasonable ratio of pointers and dimensions) V1 • V1^T is the identity and we get the same as doing the hetero-associative memory.

Similarly if we do the transform first and the cleanup afterwards we get V2^T • f(V2 • V2^T • V1 • x).

Question is, how strongly is the orthonormality constraint violated? Also, if it is violated the cleanup will also be affected. Is the effect large enough to justify the more complicated API? I assume, you use the mapping with the associative memory in Spaun?

Anyways, I wonder whether the Ivana-style hetero-associative memory might be a more common use case than the transform-style memory and if this is the case it would be good to reflect this in the API by making the hetero-associative memory easier to use or at least make it harder to accidentally use the transform-style memory.

**Comment by xchoo** [comment] 2015-11-04 20:54
The associative memory network is more a swiss-army knife. It was originally designed to do an auto-associative map (+ cleanup operation) on an input vector. However, it was a very simple extension to make it also accept hetero-associative mappings.

> Question is, how strongly is the orthonormality constraint violated? Also, if it is violated the cleanup will also be affected. Is the effect large enough to justify the more complicated API? I assume, you use the mapping with the associative memory in Spaun?

It is also dependent on the number of vectors you have in the mapping. The amount of noise added by the transform increases as the number of vectors in the vocabulary increases. The dimensionality of the vectors affect the amount of noise as well.

**Comment by jgosmann** [comment] 2015-11-04 20:58
> The amount of noise added by the transform increases as the number of vectors in the vocabulary increases. The dimensionality of the vectors affect the amount of noise as well.

But that is also true for a pure cleanup. Though, it might be sharper transition from almost no noise to a lot of noise?

**Comment by xchoo** [comment] 2015-11-04 21:00
> But that is also true for a pure cleanup. Though, it might be sharper transition from almost no noise to a lot of noise?

For a pure cleanup, the noise tolerance level can be adjusted by the user (by changing the threshold value). Using the transform, this is not possible, and the noise just accumulates in the result.

**Comment by xchoo** [comment] 2015-11-04 21:01
Also, the cleanup network helps in the case where the input vector is not "clean" (i.e. has noise added because of binding operations and what not). I don't think the transform network is able to help in that case.

**Comment by jgosmann** [comment] 2015-11-04 21:05
Note that the transform network includes a cleanup ... but I think this calls for benchmark.

**Comment by xchoo** [comment] 2015-11-04 21:07
If the transform network includes a cleanup, why not just use the associative memory network (which is just a cleanup with a different output mapping)?

**Comment by jgosmann** [comment] 2015-11-04 21:17
Because the Zen of Python: "There should be one-- and preferably only one --obvious way to do it." ;) Basically, as far as I can tell, SPA uses `transform_to` and I am trying to figure out when should I use the transform-style cleanup instead? Related question: Is it confusing if there are both ways to achieve basically the same thing for the learning Nengo user?

Also, I was thinking, that it *might* (not saying it is) be easier to simplify the API for heteroassociative memory if the transform-style cleanup needs not to be supported. Just trying to figure out the constraints which uses cases should be supported by the API.

**Comment by xchoo** [comment] 2015-11-04 21:38
The ```transform_to``` doesn't use a cleanup. Also, I'm not sure if the zen of python applies to building complex neural networks. :smile:

**Comment by xchoo** [comment] 2015-11-04 21:41
And you'd want to use the transform style mapping (it's not a cleanup) if you want a quick and dirty approximation of a mapping from one vocabulary to another. Otherwise, you'd probably want to use the associative memory style mapping.

**Comment by jgosmann** [comment] 2015-11-04 22:13
> Also, I'm not sure if the zen of python applies to building complex neural networks.

Without a good counter argument I assume it is a good guide line for now. :)

But, transform + cleanup is indeed degrading way faster. I propose to

* [ ] add some documentation how to transform between vocabs.

I also came up with a proposal on how to modify the associative memory API to make it clearer how it behaves:

Replace `AssociativeMemory(input_vocab, output_vocab=None, input_keys=None, output_keys=None, ...)` with AssociativeMemory(input_vocab, output_vocab=None, mapping=None, ...).

* This does not allow to pass in a set of keys to cleanup a subset of a vocab, but this can still be done by using `Vocabulary.create_subset()` and passing that in (which is what I did so far anyways because `input_keys` is undocumented).
* If `output_vocab` is set, but `mapping` is not, raise an exception to force the user to be explicit about what should happen.
* If `mapping='by-key'` (or something similar) do the mapping according to the keys (transform-style memory).
* To do a hetero-associative memory one passes in a dictionary with a mapping from keys in `input_vocab` to keys in `output_vocab`. (To me this seems to make it more clear how the mapping happens than two lists named `input_keys` and `output_keys`.)

Do other people think that this would be clearer, too (@ikajic?)? Any use cases not covered? Is this important enough to change a somewhat widely used piece of API (even though `input_keys` and `output_keys` should be kept and deprecated at first)?

**Comment by xchoo** [comment] 2015-11-04 23:02
I'm fine with having the specify the mapping (using a dictionary or a list of tuples, or something). 

However, there was one reason why you can specify a vocabulary and then specify a subset of keys to use (as it is in the current code base). Until the ```spa_subvocab``` branch is merged into ```master```, the way subvocabularies are handled by the spa module is non intuitive (because the subvocabulary is a separate vocabulary object altogether). With the current ```master``` codebase, you cannot specify a vocabulary for the associative memory module, and then specify that you only want a subset of the vocabulary used for the cleanup operation.

**Comment by ikajic** [comment] 2015-11-04 23:03
I agree with the idea of merging `input_keys` and `output_keys` into a single parameter. It is easier to handle one instead of two variables in the code and it is easier to check what maps to what.

It's also fairly simple to create such a dict: `dict(zip(keys1, keys2))` which shouldn't significantly pollute the code. Of course, this then needs to be handled in the `spa.AssociativeMemory`, which would imply a bit of work. Overall, I think it's worth spending some time thinking about the possible use cases, for now I can think of 'by-key' and 'one-to-one'. One of them could be set by default to avoid exception-throwing. I guess it depends largely on how the module was used so far.

**Comment by s72sue** [comment] 2015-11-04 23:08
+1 for the idea of forcing the user to be explicit about what should happen.
I also like this idea of specifying the mapping through a dictionary. 

```This does not allow to pass in a set of keys to cleanup a subset of a vocab, but this can still be done by using Vocabulary.create_subset()```

Just as in hetero-associative memory case, we can also allow the user to specify a dictionary with the subset of keys. That might be easier than creating two sub vocabs since the user will need to specify the keys while creating the sub-vocabs as well anyways.

**Comment by xchoo** [comment] 2015-11-04 23:11
> This does not allow to pass in a set of keys to cleanup a subset of a vocab, but this can still be done by using Vocabulary.create_subset().

If you use the method of providing a subvocabulary instead, when you use the spa module to connect stuff, you end up with weird results:
e.g. (This is from memory, so it may not actually compile. haha)

```
vocab = spa.Vocabulary(16)
vocab.parse('A+B+C+D')
subvocab = vocab.create_subset(['A', 'B'])

spa.am = spa.AssociativeMemory(subvocab)
spa.buf = spa.Buffer(16, vocab=vocab)

cortical = spa.Cortical('am = buf')
```

What you will find is that now both vocab and subvocab have ```'A', 'B', 'C', 'D'```, but the values for ```vocab['C']``` and ```subvocab['C']``` are not the same (also for ```'D'```).

**Comment by jgosmann** [comment] 2015-11-10 18:59
Summary from the meeting today: Everyone seems to be positive about the proposed changes. Instead of `create_subvocab` it should be possible to pass a list to `mapping` which should solve the problem @xchoo mentioned.

This all should also benefit from changing `create_subvocab` to returning a view instead of a new vocab (which is apparently a planned change?).

**Comment by jgosmann** [comment] 2017-05-09 19:35
This issue has been moved to nengo/nengo_spa#8 and nengo/nengo_spa#9.

**Closed by jgosmann** 2017-05-09 19:35 UTC
Labels: discussion, SPA
