### ISSUE TITLE
Warning on open simulators test may fail

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#1011] opened 2016-04-12 15:58 UTC
Relevant Travis-CI output [from this build](https://travis-ci.org/nengo/nengo/builds/122316947)

```
___________________________ test_warn_on_opensim_gc ____________________________

[gw0] linux2 -- Python 2.7.11 /home/travis/miniconda/envs/test/bin/python

Simulator = <class 'nengo.simulator.Simulator'>

    def test_warn_on_opensim_gc(Simulator):

        with nengo.Network() as net:

            nengo.Ensemble(10, 1)

    

        sim = Simulator(net)

        assert sim

    

        with warns(ResourceWarning):

            sim = None

>           gc.collect()

nengo/tests/test_simulator.py:117: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <nengo.utils.testing.warns object at 0x7fb0aaf8c4d0>, type = None

value = None, traceback = None

    def __exit__(self, type, value, traceback):

        if not any(r.category is self.warning_type for r in self.record):

>           self._pytest.fail("DID NOT WARN")

E           Failed: DID NOT WARN

nengo/utils/testing.py:198: Failed

============== 1 failed, 674 passed, 55 skipped in 155.97 seconds ==============
```

**Comment by jgosmann** [comment] 2016-04-22 15:20
I can't reproduce this locally, but it happen every so often on Travis-CI.

**Comment by jgosmann** [comment] 2016-04-22 19:43
Might it be better to expicitely invoke `__del__` in this test instead of implicitely relying on the reference counter/garbage collection?

**Comment by tbekolay** [comment] 2016-04-26 20:23
Huh, I never thought about calling `__del__` explicitly, but it does seem to work! I assume it just gets called again when it's actually garbage collected. I'll make a PR for it after the release (don't think it's important enough to hold it).

**Comment by jgosmann** [comment] 2016-04-26 20:49
> I assume it just gets called again when it's actually garbage collected.

Yeah, so if we would do some actual cleanup in there it could break, but it doesn't seem to be that we ever want to do that because the proper way is to do that in `close`/`__exit__`.

**Comment by tbekolay** [comment] 2016-04-26 20:59
> the proper way is to do that in close/__exit__

Good point, which reminds me that I'll call `close` after calling `__del__` just in case!

**Comment by tbekolay** [comment] 2016-06-21 18:32
Should be fixed in #1091.

**Comment by jgosmann** [comment] 2016-07-22 21:42
Unfortunately, this problem has not been solved. [See this build job.](https://travis-ci.org/nengo/nengo/jobs/145991572) Though, it is not clear to me why it failed.

**Comment by tbekolay** [comment] 2016-07-23 20:41
Hm. I see two options:

1. Switch to `pytest.warns` and see if it changes anything (my guess is no, and since it's so sporadic it might be hard to tell if this is working). We would have to bump our pytest dependency to 2.8, which is not an issue I suspect.
2. Just remove this test. If for some reason we aren't actually warning for open simulators, it's not the end of the world (not that restarting tests is the end of the world either, but it is annoying).

I'm fine with either, probably leaning toward 2 because this is our second try to get this to work robustly.

**Comment by jgosmann** [comment] 2016-07-23 21:55
2 sounds good, though I would like to understand why this isn't deterministic

**Comment by jgosmann** [comment] 2016-07-25 15:52
I think I got something like a minimal example. I created a file `x.py` with the following content:

```python
import warnings


def x():
    warnings.warn(DeprecationWarning('x'))
```

Then when I run the following code in the Python 2.7 interpreter (the bare interpreter, IPython might to some funky stuff regarding warnings):

```python
import warnings
warnings.simplefilter('always')
from x import x
x()
```

I see the warning as expected. However, with

```python
from x import x
x()
import warnings
warnings.simplefilter('always')
x()
```

I don't see any warning. So it seems another thread might produce the open sim warning before the test for it, and it fails in that case.

Next steps to investigate:
* Why is the "always" filter not working as expected? (Maybe this is intended behavior? Check with the Python docs!)
* What place are we not closing a simulator in the test? (To do so have the open sim warning raise an exception, that's probably a good thing to do anyways to ensure that backends that require the close can be tested.)

**Comment by jgosmann** [comment] 2016-07-25 15:53
Assigning this to myself to look into this later (I have other stuff with higher priority to do first). But feel free to investigate on your own if you have time.

**Comment by tbekolay** [comment] 2016-07-25 15:54
Interesting, I think raising an exception on not closing sims in testing makes sense anyhow so we should try that out.

**Comment by arvoelke** [comment] 2016-07-25 16:47
Haven't read everything here, but I saw the same thing in a nengo unit test that was just using the nengo `with warns` on something trivial. Rerunning the test fixed the issue and I haven't seen it again since. It could have something to do with the order of tests being stochastic, which as Jan showed above could result in this bug if the filter is turned on after a different test has already invoked the warning.

**Comment by tbekolay** [comment] 2016-07-25 17:15
If that's the case, then a simple fix would be to do `warnings.simplefilter('always')` in the setup of the tests so it happens before any warnings are fired.

**Comment by jgosmann** [comment] 2016-07-25 18:06
I think the culprit is [`warnings.catch_warnings` is not thread-safe](https://docs.python.org/2/library/warnings.html#available-context-managers).

**Comment by jgosmann** [comment] 2016-07-25 18:11
and `pytest.warns` doesn't seem to be thread-safe either from looking at the source

**Comment by jgosmann** [comment] 2016-07-25 18:13
Also note, that a global `warnings.simplefilter('always')` wouldn't fix the issue in this case.

**Comment by jgosmann** [comment] 2016-07-25 18:14
Also see [this issue](https://bugs.python.org/issue6647).

**Comment by arvoelke** [comment] 2016-07-25 19:44
Where is the use of threads coming from?

**Comment by tbekolay** [comment] 2016-07-25 19:48
We run `py.test` with pytest-xdist installed and pass the argument `-n 2` so that TravisCI runs the tests in two threads. It's a little bit faster, and helps uncover situations where we're doing non-threadsafe things like this.

**Comment by jgosmann** [comment] 2016-08-05 21:44
Turns out the problem is not so much the multi-threading and thread-safety of the warnings catcher (see #1136 for explanation), but this statement I found in the Python documentation:
> One thing to be aware of is that if a warning has already been raised because of a once/default rule, then no matter what filters are set the warning will not be seen again unless the warnings registry related to the warning has been cleared.

Question: How can we clear the warning registry? Is that something that we could do after we set up our filter?

Surprisingly, the open sim warning seems to be produced in tests that properly use the simulator in a `with` block like `nengo/tests/test_connection.py::test_slicing`. Not sure why that is the case ... :confused: 

Another related question is, whether we should raise exceptions for warnings (at least for some). Unfortunately, this would not make the tests fail raises the open simulator warning because the destruction of the simulator object happens too late.

**Comment by jgosmann** [comment] 2016-08-05 21:49
> Question: How can we clear the warning registry? Is that something that we could do after we set up our filter?

[Here's some code I found.](https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/_warnings.py#L9) [There is no official way to do that.](http://www.psf.upfronthosting.co.za/issue21724) [The problem might be fixed in Python >= 3.4.](http://www.psf.upfronthosting.co.za/issue4180)

**Comment by jgosmann** [comment] 2016-08-05 21:52
Related to the code link: I think the `simplefilter` call should be made before clearing the warning registry because otherwise another thread could fill it again before we set the filter.

**Comment by hunse** [comment] 2016-08-06 03:55
This was an issue in pytest, too: pytest-dev/pytest#1190. The solution currently being used there is to monkey-patch `warnings.warn` so that the warning always gets recorded (see pytest-dev/pytest#1196). It's not pretty, but it works.

What doesn't make sense to me here, is why does the warning only show up when we're using multi-threading, and then only sometimes?

**Comment by jgosmann** [comment] 2016-08-06 04:15
Unfortunately, they only do it for `deprecated_call`, so switching to `pytest.warns` won't solve the problem.

> What doesn't make sense to me here, is why does the warning only show up when we're using multi-threading, and then only sometimes?

It's actually not related to multithreading. The following code reproduces the problem without threads:
```python
import warnings

import pytest


def warn():
    warnings.warn(DeprecationWarning("test"))


@pytest.mark.parametrize('i', range(2))
def test_warning(i):
    if i % 2 == 0:
        warn()
    else:
        with pytest.warns(DeprecationWarning):
            warn()
```

But it depends on the order in which the tests are executed I suppose. Maybe the order is deterministic and works out with a single thread in Nengo, but with two threads on Travis-CI variances in the run time of single tests shuffle the order around? Still leaves the question why some tests produce the open simulator warning when they should not.

**Comment by jgosmann** [comment] 2016-08-06 04:17
Potentially the warning registry is also per thread? Then it would depend on which thread is running which tests.

**Comment by hunse** [comment] 2016-08-06 05:24
> Unfortunately, they only do it for `deprecated_call`, so switching to `pytest.warns` won't solve the problem.

I know, I wrote `pytest.warns` :) I meant that we could switch to monkey-patching in our code.

You're right in that multithreading could definitely affect test execution order, or it could have to do with which thread is running which tests. But what still doesn't make sense to me, is if the problem is that we have multiple tests (or multiple runs of the same test) issuing the same warning, then shouldn't that problem always occur when we're not using multithreading? If everything is running on one thread, then the second time the warning is issued, it should be in the registry and we should have a problem, right? It could be that the order when running on one thread is fine, and using multiple threads mixes it up sometimes. But why would order matter? If we've got two different tests issuing the same warning, then no matter which order they go in, the first test will add the warning to the registry, and the second one will fail.

The only thing I can think of is that there are two tests that issue the same warning: in one, the warning is issued but not checked for, and in the other it is issued and checked for. If the first test is run before the second we have a problem, but if they go in the other order we don't. On second thought, that doesn't seem that far-fetched. That could be what's happening.

**Comment by jgosmann** [comment] 2016-08-06 14:38
> in one, the warning is issued but not checked for, and in the other it is issued and checked for

Yes, that is what's happening. It is just unclear why the warning is issued in some of the tests.

**Comment by hunse** [comment] 2016-08-06 15:48
Or it could be that it's something about the multithreading that is causing the simulators to not close properly, and hence the warning to be issued.

Either way, I think if we monkey-patch `warnings.warn` then we'll be okay. It would still be nice to figure out why the warning is being issued, but that seems like a separate issue.

**Comment by jgosmann** [comment] 2016-08-06 15:50
> Or it could be that it's something about the multithreading that is causing the simulators to not close properly, and hence the warning to be issued.

No, I'm getting those warnings even without multithreading.

**Comment by tbekolay** [comment] 2016-08-07 14:09
Monkey-patching `warnings.warn` makes sense to me! Should `pytest.warns` so that as well? Ideally, we'd monkey-patch it in Nengo, make a PR to pytest to do that in `pytest.warns` as well, then once that's merged and released switch to `pytest.warns` and up our pytest dependency. I can make these changes if others haven't started on it yet.

**Comment by jgosmann** [comment] 2016-08-08 02:42
Haven't started on it yet and probably won't after I'm back from CogSci. So feel free to code ahead.

**Comment by hunse** [comment] 2016-08-09 21:22
Making a PR to `pytest` sounds good. I'm trying to think if there are any downsides to monkeypatching. The only two that I can think of are a) it doesn't take warning filters into account, which could be good or bad depending on the situation, and b) if anything has stored a reference to `warnings.warn`, then it won't work.

**Comment by tbekolay** [comment] 2016-08-09 21:26
> it doesn't take warning filters into account

True, but the implementation there already does `warnings.simplefilter('always')` so that must not be a common use case (or they'd have bug reports).

> if anything has stored a reference to warnings.warn, then it won't work.

Right, and this would be the case when people do `from warnings import warns`. So I guess the more robust solution for pytest might be to explicitly clear out the warnings registry?

**Closed** 2016-08-10 12:49 UTC
Labels: bug

**Comment by hunse** [comment] 2016-08-10 13:24
The other thing to look at is [`pytest-warnings`](https://github.com/fschulze/pytest-warnings/blob/master/pytest_warnings.py). It's an addon for `pytest` and it looks like it overloads `showwarning` to record shown warnings.
