### ISSUE TITLE
Re-addding a component to spa.SPA chrashes it

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo#897] opened 2015-11-16 17:35 UTC
Minimal example from Jupyter notebook:
```python
D=16
vocab1 = spa.Vocabulary(D)
vocab1.parse('A+B+C')

with spa.SPA('AssociativeMemory', seed=1) as model_1:
    model_1.assoc_mem = spa.AssociativeMemory(input_vocab=vocab1)
```

In another cell:
```python 

with model_1:
    model_1.net_input = spa.Input(assoc_mem='A')
```

When **re-running** the second cell the network crashes with:
```python
ValueError: <Input "net_input"> was not added as an attribute of the SPA network and won't be detected
```

**Comment by Seanny123** [comment] 2015-11-16 17:39
For an even more basic example:
```
import nengo
from nengo import spa

D = 16
model = spa.SPA()

with model:
    model.state = spa.State(D)

with model:
    model.state = spa.State(D)
```

**Comment by jgosmann** [comment] 2015-11-16 17:42
@Seanny123 In your example your reassigning `model.state`. In that case the exception might be intended behaviour. In @ikajic's example a different attribute is assigned and raising an exception there is definitely a bug.

**Comment by jgosmann** [comment] 2015-11-16 17:43
Also, I can run @ikajic's example without any problems.

**Comment by Seanny123** [comment] 2015-11-16 18:57
After some discussion, Terry, Jan, Ivana and I concluded that re-assignment of module-attributes should not be allowed. This is because of potential for confusion caused by re-assignment of modules after they've been used in Actions or Inputs. Consequently, an error should be thrown.

**Closed** 2016-02-26 16:17 UTC
Labels: bug
