### ISSUE TITLE
Control learning rate

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo#769] opened 2015-07-03 21:02 UTC
At the moment it is not possible to control the learning rate within the simulation through an ensemble. Being able to do so might be useful for me. With PES it is possible to inhibit the error population, but that is not possible with BCM.

**Comment by arvoelke** [comment] 2015-07-03 21:22
Note: See https://github.com/nengo/nengo/pull/727/files#diff-d4a1ea7c740725a930af968ec8143735R154 for an example of how this was done with the Voja unsupervised learning rule.

**Comment by tbekolay** [comment] 2016-12-12 15:54
There's discussion of possible ways to implement this in #427. Closing this as a duplicate of that issue; anyone interested in this should go there and contribute to the discussion!

**Closed by tbekolay** 2016-12-12 15:54 UTC
Labels: feature request
