### ISSUE TITLE
Implement Parisien transform

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo#692] opened 2015-03-23 13:47 UTC
This is a feature in 1.4 and is described here: http://compneuro.uwaterloo.ca/publications/parisien2008.html

It allows any circuit to respect Dale's principle (i.e. neurons are either excitatory or inhibitory, not both).  Nice feature to have for bioplausibility claims and comparison to certain kinds of data.

**Comment by jgosmann** [comment] 2016-05-05 20:16
Duplicate of #921.

**Closed by jgosmann** 2016-05-05 20:16 UTC
Labels: feature request
